### ISSUE TITLE
Test scholastically fails in Python 3.5

### ISSUE THREAD

**Issue by babbush** [ProjectQ-Framework/FermiLib#12]
The third test in _plane_wave_hamiltonian_test seems to fail occasionally in Python 3.5. This is shown here: https://travis-ci.org/ProjectQ-Framework/FermiLib/jobs/230235580

The origin of this failure is not clear. We should get to the bottom of it.

**Comment by damiansteiger** [comment]
Can someone reproduce the failure on his machine? It only shows up randomly.

**Comment by babbush** [comment]
I have not been able to reproduce locally and I have tried. I might note that Wei Sun's recent pull request changed the code being tested here as well as the test that sometimes fails. It is possible that his changes fixed the problem but since we don't know the cause of the bug, we can't know for sure.

**Comment by babbush** [comment]
We haven't seen a failure since Wei Sun's last pull request so for now I will close this issue.
