### ISSUE TITLE
Time for new release?

### ISSUE THREAD

**Issue by babbush** [ProjectQ-Framework/FermiLib#154]
We might want to consider making a new non-alpha release. Now that OpenFermion is out, if we are going to keep FermiLib around, moving it out of alpha makes some sense to me. @damiansteiger and @thomashaener, thoughts?

**Comment by damiansteiger** [comment]
Of course we can make a first beta release or another alpha release, both are fine with me.

To move forward to a 0.1 release, we would have to invest considerably more time in my opinion to
* Fix a couple of things (such as e.g. the use of marshal #124 )
* Perform a complete code review of all files and fix all the things which might come up there
* Another manual test of the code on Windows
* Same things for the plugins
* ...

Given my time budget, I don't see that happening in the next days (except another alpha or beta release).

**Comment by babbush** [comment]
let's move to beta then. I also do not have time to keep working on FermiLib (opposed to OpenFermion) except for very small things here and there.

**Comment by damiansteiger** [comment]
Sounds good. We will make a beta release tomorrow.

**Comment by babbush** [comment]
:+1:

**Comment by damiansteiger** [comment]
I looked up again all the recent changes. There aren't enough new features to justify a new pre-release and we want to fix a few of the above things before making the next release. As users can always install the latest version from GitHub that should be fine.
