### ISSUE TITLE
HDF5 should save the arrays in MolecularData

### ISSUE THREAD

**Issue by babbush** [ProjectQ-Framework/FermiLib#23]
Currently, the class MolecularData can save and store information using an HDF5 container. But some information, in particular arrays that can grow to be large like the integrals, RDMs and CC amplitudes are stored independently as numpy arrays. The logic behind this made sense for earlier versions of the code where we used pickle. Because sometimes you want to load some information but not all of it. However, the HDF5 container already has the property that it only loads the data you ask for. Accordingly, we should make sure that all data is saved in one HDF5 file.

**Comment by jarrodmcc** [comment]
This was resolved in #66
