### ISSUE TITLE
Develop needs to be default branch

### ISSUE THREAD

**Issue by babbush** [ProjectQ-Framework/FermiLib#27]
Two people today have accidentally pulled into master. Also, the develop code is fairly stable. Let's please make that change.

**Comment by ncrubin** [comment]
This can be changed by someone who is listed as a contributor.  Under settings/branches the default branch can be changed to `develop` and the protected branch can be set to `master`.

**Comment by damiansteiger** [comment]
The default branch has been changed to develop.
We will test how this works.
