### ISSUE TITLE
Running tests causes changes to `src/fermilib/data/dummy_molecule.hdf5`

### ISSUE THREAD

**Issue by Strilanc** [ProjectQ-Framework/FermiLib#46]
Tests shouldn't be making changes to source files.

If this indicates a problem, then the test should be failing instead of editing the file.

**Comment by babbush** [comment]
Well actually I think that test is literally changing the file, loading it, and then changing it back and saving it. It's not the best solution but the point of the test that is doing this is to test the save/load functionality. So I don't really know how to avoid that.

**Comment by Strilanc** [comment]
If the test is supposed to check that you can load a legacy file, it should not overwrite the file.

If the test is supposed to check that can load a current file, you should save a new file, load it, then delete it.

In neither case should a file end up changed or created by the test.

**Comment by babbush** [comment]
The test that does this should then save a new file and then load it, then delete it. I am in favor of changing the test this way. The test that does this is test_dummy_save in _molecular_data_test.py in utils.
